
plugins:
    - react

extends:
    - plugin:react/recommended
    - benoitz

rules:
    no-console: off
    react/prop-types: off
    react/no-unknown-property: off

env:
    node: true
    browser: true

globals:
    __DEV__: false

settings:
    react:
      pragma: h

